### ISSUE TITLE
[56]byte padding question

### ISSUE THREAD

**Issue by GeorgeErickson** [jakewins/4fq#3]
Not actually an issue. I'm curious why you pad with 56 bytes on each side [here](https://github.com/jakewins/4fq/blob/e7be76fd926a5350b1d936297065c97d9a502458/pkg/queue/queue.go#L82-L84)

```go
type sequence struct {
	_lpad [56]byte
	value int64
	_rpad [56]byte
}
```

**Comment by jakewins** [comment]
Sorry for super late reply, apparently I don't have notifications set up properly. It's to force the value to sit on a dedicated cache line in RAM; without this, two queues could end up sharing the same cache line, which tanks performance since the writes to the two values end up behaving as if it were contended writes to the same value;

https://dzone.com/articles/false-sharing

**Comment by GeorgeErickson** [comment]
Thanks :) 

I was mainly wondering why you choose 56 bytes of padding on each side. So each sequence takes up `56 + 8 + 56 = 120 bytes` don't you want to be aligned to 128?

```go
type sequence struct {
    value int64
    _pad [120]byte
```

I could be very wrong
